#pragma once

#include "String.h"

const String RESOURCES = "./resources/";
const String RESOURCES_ENGINE = RESOURCES + "engine/";
const String RESOURCES_ENGINE_ANIMATIONS = RESOURCES_ENGINE + "animations/";
const String RESOURCES_ENGINE_FONTS = RESOURCES_ENGINE + "fonts/";
const String RESOURCES_ENGINE_MESHES = RESOURCES_ENGINE + "meshes/";
const String RESOURCES_ENGINE_SHADERS = RESOURCES_ENGINE + "shaders/";
const String RESOURCES_ENGINE_TEXTURES = RESOURCES_ENGINE + "textures/";
const String RESOURCES_ENGINE_TEXTURES_UI = RESOURCES_ENGINE_TEXTURES + "ui/";
const String RESOURCES_ENGINE_TEXTURES_UI_ANIMATION_EDITOR = RESOURCES_ENGINE_TEXTURES_UI + "animation_editor/";
