#pragma once

#include "Engine/Paths.h"

const String RESOURCES_MESHES_TILES = RESOURCES_MESHES + "tiles/";
const String RESOURCES_MESHES_CHARACTERS = RESOURCES_MESHES + "characters/";
const String RESOURCES_MESHES_ITEMS = RESOURCES_MESHES + "items/";
const String RESOURCES_TEXTURES_CHARACTERS = RESOURCES_TEXTURES + "characters/";
const String RESOURCES_TEXTURES_ITEMS = RESOURCES_TEXTURES + "items/";
const String RESOURCES_TEXTURES_TILES = RESOURCES_TEXTURES + "tiles/";
const String RESOURCES_TEXTURES_COMPLEXTILES = RESOURCES_TEXTURES + "complex_tiles/";
const String RESOURCES_AUDIO = RESOURCES + "audio/";
const String RESOURCES_AUDIO_MUSIC = RESOURCES_AUDIO + "music/";
const String RESOURCES_AUDIO_EFFECTS = RESOURCES_AUDIO + "effects/";
const String RESOURCES_AUDIO_AMBIENT = RESOURCES_AUDIO + "ambient/";
