#pragma once

#include "Engine/Paths.h"

const String RESOURCES_HEXA = RESOURCES + "hexagame/";
const String RESOURCES_HEXA_ANIMATIONS = RESOURCES_HEXA + "animations/";
const String RESOURCES_HEXA_FONTS = RESOURCES_HEXA + "fonts/";
const String RESOURCES_HEXA_MESHES = RESOURCES_HEXA + "meshes/";
const String RESOURCES_HEXA_MESHES_CHARACTERS = RESOURCES_HEXA_MESHES + "characters/";
const String RESOURCES_HEXA_MESHES_ITEMS = RESOURCES_HEXA_MESHES + "items/";
const String RESOURCES_HEXA_SHADERS = RESOURCES_HEXA + "shaders/";
const String RESOURCES_HEXA_TEXTURES = RESOURCES_HEXA + "textures/";
const String RESOURCES_HEXA_TEXTURES_CHARACTERS = RESOURCES_HEXA_TEXTURES + "characters/";
const String RESOURCES_HEXA_TEXTURES_ITEMS = RESOURCES_HEXA_TEXTURES + "items/";
const String RESOURCES_HEXA_TEXTURES_TILES = RESOURCES_HEXA_TEXTURES + "tiles/";
const String RESOURCES_HEXA_TEXTURES_UI = RESOURCES_HEXA_TEXTURES + "ui/";
